openapi: 3.0.0
info:
  title: APNIC REX Economies and Resources API
  description: API for accessing detailed economies data and resource information.
  version: 1.0.0
servers:
  - url: https://rex.apnic.net/
    description: APNIC REX API server
paths:
  
  /economies.json:
    get:
      operationId: getEconomies
      summary: Get economies data
      responses:
        '200':
          description: A JSON object of economy data
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Add specific properties according to the actual API response
